version: 2

project_name: allingo

builds:
  - skip: true

source:
  enabled: true
  format: tar.gz
  name_template: "{{ .ProjectName }}_{{ .Version }}_source"

checksum:
  name_template: checksums.txt

release:
  draft: false
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
